# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-14 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_url', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_url', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NameProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_url', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=10, unique=True)),
                ('brends', models.SmallIntegerField(blank=True, default=0)),
                ('season_id', models.SmallIntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('wholesale_price', models.FloatField(blank=True, default=0)),
                ('purshase_price', models.FloatField(blank=True, default=0)),
                ('main_photo_path', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField(blank=True, default='')),
                ('caption', models.CharField(default='', max_length=200)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('discount', models.SmallIntegerField(blank=True, default=0)),
                ('price_down', models.SmallIntegerField(blank=True, default=0)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.FloatField(blank=True, default=0)),
                ('empty_count', models.BooleanField(default=False)),
                ('seo_attributes', models.TextField(blank=True, default='')),
                ('is_belarus', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_new_date_end', models.DateField(auto_now_add=True)),
                ('link_name', models.CharField(max_length=550)),
                ('identifier', models.CharField(max_length=20)),
                ('dirname_img', models.CharField(blank=True, default='', max_length=25)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsstore.MainCategory')),
                ('nameproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsstore.NameProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_url', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SizeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField(default=0)),
                ('count_num', models.SmallIntegerField(default=0)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizecount', to='dsstore.Products')),
            ],
        ),
        migrations.CreateModel(
            name='SizeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('height', models.SmallIntegerField()),
                ('chest', models.SmallIntegerField()),
                ('waist', models.SmallIntegerField()),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsstore.MainCategory')),
            ],
            options={
                'ordering': ['height'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='dsstore.Products'),
        ),
    ]
