# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-15 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizetable',
            name='maincategory',
        ),
        migrations.DeleteModel(
            name='SizeTable',
        ),
    ]
