# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsstore', '0002_auto_20171115_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeTableNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('height', models.SmallIntegerField()),
                ('chest', models.SmallIntegerField()),
                ('waist', models.SmallIntegerField()),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsstore.MainCategory')),
            ],
        ),
    ]
