# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsstore', '0005_sizetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_url', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sizetable',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
