# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-24 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dsstore', '0007_auto_20171121_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True)),
                ('wholesale_price', models.FloatField(blank=True)),
                ('purshase_price', models.FloatField(blank=True)),
                ('main_photo_path', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField()),
                ('color', models.CharField(blank=True, max_length=100)),
                ('discount', models.SmallIntegerField(blank=True)),
                ('price_down', models.SmallIntegerField(blank=True)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.FloatField(blank=True, default=0)),
                ('empty_count', models.BooleanField(default=False)),
                ('seo_attributes', models.TextField()),
                ('is_belarus', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_new_date_end', models.DateField(default=datetime.datetime(2017, 11, 23, 8, 27, 39, 533814, tzinfo=utc))),
                ('link_name', models.CharField(max_length=550)),
                ('identifier', models.CharField(max_length=20)),
                ('dirname_img', models.CharField(blank=True, default='', max_length=25)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('brends', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='dsstore.Brends')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsstore.MainCategory')),
                ('nameproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsstore.NameProduct')),
                ('season', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='dsstore.Seasons')),
            ],
        ),
        migrations.CreateModel(
            name='SizeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField(default=0)),
                ('count_num', models.SmallIntegerField(default=0)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsstore.Products')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='dsstore.Products'),
        ),
    ]
