# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-14 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dsstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=10)),
                ('count_num', models.SmallIntegerField(default=0)),
                ('size', models.SmallIntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('place_sale', models.SmallIntegerField(default=1)),
                ('date_sale', models.DateField(auto_now_add=True)),
                ('link_name', models.CharField(max_length=550)),
                ('oreder_status', models.SmallIntegerField(blank=True, default=1)),
                ('declaration_number', models.CharField(blank=True, default='', max_length=150)),
                ('date_send', models.DateField()),
                ('is_return', models.BooleanField(default=False)),
                ('date_return', models.DateField()),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psale', to='dsstore.Products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productssale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
